---
- block:

  - name: install redis
    become: yes
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - redis

  - name: redis boot and restart
    become: yes
    systemd:
      name: redis
      state: restarted
      daemon_reload: yes
      enabled: yes

  tags:
    - redis
