---
- block:

  - name: install enhancd
    git:
      repo: https://github.com/b4b4r07/enhancd.git
      dest: "~/.enhancd"

  - name: add enhancd environment
    blockinfile:
      dest: "{{shell_file_path}}"
      create: yes
      state: present
      content: |
        source ~/.enhancd/init.sh
        NHANCD_FILTER=peco
        export ENHANCD_FILTER

  tags:
    - enhancd
