---
- block:

  - name: uninstall mariadb-libs
    become: yes
    yum:
      name: mariadb-ribs
      state: absent

  - name: install packages
    become: yes
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - tree
      - unzip
      - ctags
      - dstat
      - telnet
      - libselinux-python
      - the_silver_searcher
      - mysql-devel
      - gcc-c++

  tags:
    - packages
