---
- block:

  - name: install packages
    become: yes
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - tree
      - ctags
      - dstat
      - telnet
      - libselinux-python
      - the_silver_searcher

  tags:
    - packages
