---
- block:

  - name: change shell to zsh
    become: yes
    user:
      name: "{{user}}"
      shell: "{{zsh.path}}"
      state: present
  
  - name: install prezto
    git:
      repo: https://github.com/sorin-ionescu/prezto.git
      dest: "{{home}}/.zprezto"
  
  - name: add symbolic link dotfiles
    file: 
      src: "{{home}}/.zprezto/runcoms/{{item}}"
      dest: "{{home}}/.{{item}}"
      state: "link"
    with_items:
      - zlogin
      - zlogout
      - zshrc
      - zpreztorc
      - zprofile
      - zshenv

  - name: set prompt theme
    lineinfile:
      dest: "{{home}}/.zprezto/runcoms/zpreztorc"
      regexp: "':prezto:module:prompt' theme"
      line: "zstyle ':prezto:module:prompt' theme 'steeef'"

  - name: add module
    blockinfile:
      dest: "{{home}}/.zprezto/runcoms/zpreztorc"
      content: |
        zstyle ':prezto:load' pmodule \
          'environment' \
          'terminal' \
          'editor' \
          'history' \
          'directory' \
          'spectrum' \
          'utility' \
          'completion' \
          'git' \
          'docker' \
          'autosuggestions' \
          'syntax-highlighting' \
          'history-substring-search' \
          'prompt'

  tags:
    - prezto
