---
- block:

  - name: install pip
    become: yes
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - python-pip

  - name: pip upgrade and install awscli
    shell: pip install --upgrade awscli --user

  - name: add .local bin to PATH
    lineinfile:
      dest: "{{shell_file_path}}"
      create: yes
      state: present
      line: "export PATH=$HOME/.local/bin:$PATH"

  - name: include aws cli config
    include_tasks: config.yml

  tags:
    - awscli
