---
- block:

  - name: install packages
    become: yes
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - ncurses-devel

  - name: exist zsh
    stat:
      path: "{{zsh.path}}"
    register: exist_zsh

  # - name: download zsh
  #   when: not exist_zsh.stat.exists
  #   become: yes
  #   git:
  #     repo: https://github.com/zsh-users/zsh.git
  #     dest: /tmp/zsh

  - name: download zsh
    when: not exist_zsh.stat.exists
    become: yes
    get_url:
      url: https://sourceforge.net/projects/zsh/files/zsh/{{zsh.version}}/zsh-{{zsh.version}}.tar.xz/download
      dest: /tmp/zsh-{{zsh.version}}.tar.gz

  - name: unzip zsh
    when: not exist_zsh.stat.exists
    unarchive:
      src: /tmp/zsh-{{zsh.version}}.tar.gz
      dest: /tmp
      copy: no

  - name: make install zsh
    when: not exist_zsh.stat.exists
    become: yes
    shell: ./configure && make && sudo make install
    args:
      chdir: /tmp/zsh-{{zsh.version}}

  - name: add zsh path to shell
    # when: not exist_zsh.stat.exists
    become: yes
    lineinfile:
      dest: /etc/shells
      state: present
      line: "{{zsh.path}}"

  - name: change shell to zsh
    # when: not exist_zsh.stat.exists
    become: yes
    user: name={{user}} shell={{zsh.path}} state=present
  
  tags:
    - zsh
